# 파이참
# import 패키지명.프로젝트명 from 함수이름(매개변수)
print("Hello python")
print("Hello")
print("master")
print("master")
print("branch hotfix")
print("branch hotfix")
print("branch hotfix")
print("branch hotfix")
print("branch hotfix")
print("branch hotfix")
print("master")

print("master")